version: '3.8'
services:
  sqlitebrowser:
    image: lscr.io/linuxserver/sqlitebrowser:latest
    container_name: sqlitebrowser
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
      - ./server:/config/db
    ports:
      - 3000:3000
      - 3001:3001
    restart: unless-stopped